export const Colors={
    statusbarcolor:'#ff0000',
    internetbackcolor:'green',
    onlinebackcolor:'green',
    internettextcolor:'#FFFFFF',
    onlinetextcolor:'#FFFFFF',
    mediabackground:'#FFFFFF',
    mediatextcolor:'black',
    cancletextcolor:'black',
    buttoncolor:'red',
    whiteColor:'#FFFFFF',
    blackColor:'#000000',
    greyColor:'gray',
    Otpresedcolor:'green',
    otpcountcolor:'red',
    otpverifycolor:'#1985ff',

    theme_color3:'#ca7e51',
    theme_color2:'#24a7c3',
    theme_color1:'#ff0000',
    facebook_color:'#3B5998',
    google_color:'#4285F4',
    apple_color:'#464647',
    loginbg_color:'#24A7C3',
    loginbg2_color:'#E2D437',
    logingreen_color:'#96A917',
    border_color:'#eceded',
    border_color1:'#8b8b8b',
    red_color:'red',
    logoutbgcolor:'#FEE9E9',
    homebg:'#F1F4E1',
    homebg1:'#178CA5',
    silver:'#E6E3E4',
    yellow:'yellow',
    drwrfont:'#474747',
    orderbg:'#FFED9A',
    orderplacebg:'#DAE4FF',
    edittextbg:'#F7F3C7',
    drwerbg:'#E6F2C5',
    lightfontcolor: '#b9b9b9',
    newcolor:'#e4e4e4',
    newcolor1:'#e7e7e7',

    /*************Ticket**************/
    colorTicket: '#dfdfdf',
    colorTicketButton: '#e9e9e9',
    colorTicketSelected: '#ec395b',
    colorDateItem: '#848484',
    colorHomeItem: '#e5e5e5',
    colorTicketItem: '#f4f4f4',
    colorTicketDescription: '#686868',
    colorTicketTotal: '#d9d9d9',
    colorTicketE2: '#e2e2e2',
    colorTicketD5: '#d5d5d5',
    colorTicketButtonRed: '#e31f26',
    colorTicketBlue01: '#146d77',
}
export const Font={
    Poppins_ExtraBold:'Poppins-Bold',
    Poppins_Bold:'Poppins-Bold',
    Poppins_SemiBold:'Poppins-SemiBold',
    Poppins_Regular:'Poppins-Regular'
}
