
export const localimag={
    splashbg:require('../icons/splashscreen.png'),
    nopreview:require('../icons/nopreview.png'),
    splashbg1:require('../icons/bg.png'),
    splash:require('../icons/airseekrlogo4.png'),
    splash3:require('../icons/airseekrlogo3.png'),
    splash2:require('../icons/airseekrlogo2.png'),
    splash1:require('../icons/Logo-Final_1024x1024-Airseekr-dark.png'),
    emailicon:require('../icons/mailicon.png'),
    passwordicon:require('../icons/passwordicon.png'),
    fbicon:require('../icons/fbicon.png'),
    googleicon:require('../icons/googleicon.png'),
    appleicon:require('../assets/appleicon.png'),
    backarrowicon:require('../icons/backarrowicon.png'),
    backw:require('../icons/backarrowicon.png'),
    nameicon:require('../icons/nameicon.png'),
    phoneicon:require('../icons/phoneicon.png'),
    locationicon:require('../icons/locationicon21.png'),
    notificationicon:require('../icons/notificationicon.png'),
    notificationss:require('../icons/notificationss.png'),
    settingicon:require('../icons/settingicon.png'),
    settingicon1:require('../icons/settingicon1.png'),
    favouriteicon:require('../icons/favouriteicon.png'),
    deactivefavicon:require('../icons/deactivefavicon.png'),
    searchicon:require('../icons/searchicon.png'),
    search1:require('../icons/search1.png'),
    arrowred:require('../icons/arrowred.png'),
    dotsb:require('../icons/dotsb.png'),
    clockicon10:require('../icons/clockicon10.png'),
    redoffericon:require('../icons/redoffericon.png'),
    messageicon29:require('../icons/messageicon29.png'),
    crossw:require('../icons/crossw.png'),
    greycameraicon:require('../icons/greycameraicon.png'),
    plus:require('../icons/plus.png'),
    whitebackarrow:require('../icons/whitebackarrow.png'),
    arroww:require('../icons/arroww.png'),
    crossicon:require('../icons/crossicon.png'),
    productarrowicon:require('../icons/productarrowicon.png'),
    selectarrowicon:require('../icons/selectarrowicon.png'),
    locationicon:require('../icons/locationicon.png'),
    editarrowicon:require('../icons/editarrowicon.png'),
    editicon:require('../icons/editicon.png'),
    mailwhiteicon:require('../icons/mailwhiteicon.png'),
    sellericon:require('../icons/sellericon.png'),
    settingprofileicon:require('../icons/settingprofileicon.png'),
    editidverification:require('../icons/editidverification.png'),
    bankbuilding:require('../icons/bank-building.png'),
    termsconditionsicon:require('../icons/termsconditionsicon.png'),
    privacypolicyicon:require('../icons/privacypolicyicon.png'),
    aboutus:require('../icons/aboutus.png'),
    contacticon:require('../icons/contacticon.png'),
    shareicon:require('../icons/shareicon.png'),
    contacticon:require('../icons/contacticon.png'),
    rateappicon:require('../icons/rateappicon.png'),
    cameraicon:require('../icons/cameraicon.png'),
    logouticon:require('../icons/logouticon.png'),
    sendicon:require('../icons/sendicon.png'),
    addicon:require('../icons/addicon.png'),
    checkchat:require('../icons/checkchat.png'),
    check:require('../icons/check.png'),
    congrateright:require('../icons/congrateright.png'),
    share:require('../icons/share.png'),
    myadsactaive:require('../icons/myadsactaive.png'),
    homeactive:require('../icons/homeactive.png'),
    chatactive:require('../icons/chatactive.png'),
    profileacative:require('../icons/profileacative.png'),
    calender:require('../icons/calender.png'),
    blackoffericon:require('../icons/blackoffericon.png'),
    cross:require('../icons/cross.png'),
    user_profile:require('../icons/user_profile.png'),
    user_profile1:require('../icons/user_profile1.png'),
    nodata:require('../icons/nodata.png'),
    footerimage:require('../icons/footerimage.png'),
    leftarrow:require('../icons/leftarrow.png'),
    editicon1:require('../icons/editicon1.png'),







    //------------------removable--------------------//
    Group24:require('../icons/Group24.png'),
    backbg:require('../icons/backbg.png'),
    addunselect:require('../icons/addunselect.png'),
    addselect:require('../icons/addselect.png'),

  //------------------removable--------------------//

    deactivatehomeicon:require('../icons/deactivatehomeicon.png'),
    addsicon:require('../icons/addsicon.png'),
    posticon:require('../icons/posticon.png'),
    chaticon:require('../icons/chaticon22.png'),
    profileicon:require('../icons/profileicon.png'),


    //------------------removable--------------------//
    backIcon2: require('../assets/back-icon.png'),


    visaCard: require('../assets/visa-credit-card.png'),
    paypal: require('../assets/paypal.png'),
}
